name: taxi_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  firebase_analytics: ^10.10.6
  firebase_core: ^2.31.1
  firebase_messaging: ^14.9.3
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^17.1.2
  flutter_native_splash: ^2.4.0
  flutter_rating_bar: ^4.0.1
  flutter_secure_storage: ^9.1.1
  font_awesome_flutter: ^10.7.0
  geocoding: ^3.0.0
  geolocator: ^11.0.0
  go_router: ^14.0.0
  google_maps_flutter: ^2.6.1
  http: ^1.2.1
  loading_animation_widget: ^1.2.1
  modal_bottom_sheet: ^3.0.0
  permission_handler: ^11.3.1
  provider: ^6.1.2
  url_launcher: ^6.3.0
  uuid: ^4.4.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/icon.png"

flutter_native_splash:
  color: "#42a5f5" # El color de fondo del splash screen.
  image: assets/images/splash1.jpg # La ruta de la imagen del splash screen.
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center

flutter:
  uses-material-design: true

  assets:
    - assets/imgbackgrounds/
    - assets/logo/
    - assets/

  fonts:
    - family: agressive
      fonts:
        - asset: fonts/agressive.otf
